// <auto-generated />
namespace kenzauros.RHarbor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddSortOrderColumnToExternalProgramDefinition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSortOrderColumnToExternalProgramDefinition));
        
        string IMigrationMetadata.Id
        {
            get { return "202201080828501_AddSortOrderColumnToExternalProgramDefinition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
